"""Live execution against a running Tasker instance (optional).

Idea adapted (not copied) from dceluis/tasker-mcp: the MCP triggers a task that
already exists on the phone via an HTTP POST to Tasker's HTTP server
(default port 1821). This module has NO third-party dependencies (stdlib urllib)
and is fully opt-in: it only works if TASKER_HOST / TASKER_API_KEY are configured.

This repo's job is to DESIGN and GENERATE validated Tasker XML. Live execution is
a convenience on top: once a task is imported on the phone, the LLM can trigger it.

Environment variables:
    TASKER_HOST      Host/IP of the phone running Tasker (e.g. 192.168.1.123)
    TASKER_PORT      Tasker HTTP server port (default: 1821)
    TASKER_API_KEY   Tasker API key (tk_...), generated by the "MCP generate_api_key" task

See docs/integracion-dceluis.md for the full picture.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Any, Optional


class TaskerLiveError(Exception):
    """Raised when a live Tasker call cannot be made or fails."""


def is_configured() -> bool:
    """True if the minimum config for live execution is present."""
    return bool(os.environ.get("TASKER_HOST") and os.environ.get("TASKER_API_KEY"))


def _config() -> tuple[str, str, str]:
    """Return (host, port, api_key), raising if host/api_key are missing."""
    host = os.environ.get("TASKER_HOST", "").strip()
    port = os.environ.get("TASKER_PORT", "1821").strip() or "1821"
    api_key = os.environ.get("TASKER_API_KEY", "").strip()
    if not host:
        raise TaskerLiveError(
            "TASKER_HOST is not set. Live execution is disabled. "
            "Set TASKER_HOST and TASKER_API_KEY to enable it."
        )
    if not api_key:
        raise TaskerLiveError(
            "TASKER_API_KEY is not set. Live execution is disabled. "
            "Generate one on the phone with the 'MCP generate_api_key' task."
        )
    return host, port, api_key


def run_task(
    task_name: str,
    arguments: Optional[dict[str, Any]] = None,
    timeout: float = 15.0,
) -> str:
    """Trigger a task that already exists in Tasker on the phone.

    Sends POST http://<host>:<port>/run_task with a JSON body
    {"name": <task_name>, "arguments": {...}} and Bearer auth.

    Args:
        task_name: Exact Tasker task name (as it appears on the phone).
        arguments: Optional dict of arguments passed to the task.
        timeout: Seconds to wait for Tasker to respond.

    Returns:
        The response body from Tasker as a string.

    Raises:
        TaskerLiveError: if not configured, on network error, or on HTTP error.
    """
    host, port, api_key = _config()
    url = f"http://{host}:{port}/run_task"

    payload = json.dumps(
        {"name": task_name, "arguments": arguments or {}}
    ).encode("utf-8")

    req = urllib.request.Request(url, data=payload, method="POST")
    req.add_header("Content-Type", "application/json")
    req.add_header("Authorization", f"Bearer {api_key}")

    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="replace")
            return body if body else f"OK (task '{task_name}' triggered, empty body)"
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace") if e.fp else ""
        raise TaskerLiveError(
            f"Tasker returned HTTP {e.code} for task '{task_name}': {detail}"
        ) from e
    except urllib.error.URLError as e:
        raise TaskerLiveError(
            f"Could not reach Tasker at {url}: {e.reason}. "
            "Is the phone on the network and the Tasker HTTP server running?"
        ) from e
